### ISSUE TITLE
Create Account and Link Account are not mutually exclusive

### ISSUE THREAD

**Issue by Aranad** [saul-avikar/wordpress-blockstack-sso#2]
Account creation is optional because not all sites want to allow the public to register their own accounts. The account linking however does not need to be optional, it can only be done by the owner of the account so is safe to make it always available.

There's no reason why a site that has the ability for accounts to be created publicly should not also be able to allow account linking - account linking should always be available.

Also the other option of allowing custom user names should really be the default, I don't think any site would really want to use public keys for user names.

**Comment by saul-avikar** [comment]
525ae1de21036249f2607f34e417924df9b8291c, f9edb63dcbc2899d970e363f83d8066ad2474a38

**Comment by saul-jb** [comment]
1b79b5e8450b516b8b28b84081bbaaeba71c10b4 e5208bff071a028e24fa89f5bfd5e3f5372ea8b4
