### ISSUE TITLE
Change text to i18n

### ISSUE THREAD

**Issue by Aranad** [saul-avikar/wordpress-blockstack-sso#3]
Best to start internationalising your code from the outset while there's less work to do... it means not writing your test directly into the script, but rather using functions that select text from files depending on the user's language. Here's an intro of how Wordperss does it.
https://codex.wordpress.org/I18n_for_WordPress_Developers

**Comment by saul-jb** [comment]
525ae1de21036249f2607f34e417924df9b8291c f9edb63dcbc2899d970e363f83d8066ad2474a38
