### ISSUE TITLE
Sign in with Blockstack button does not work

### ISSUE THREAD

**Issue by blockpac** [saul-avikar/wordpress-blockstack-sso#5]
Is this plugin still under active development? Am testing it but when clicking on the 'Sign in with Blockstack' button nothing happens.

**Comment by saul-jb** [comment]
Hi,

First of all can you verify that these conditions are met:
- The website running under https
- You have the Blockstack common libs somewhere where the web server has access to it  (https://github.com/saul-avikar/blockstack-sso)
- The Blockstack common lib paths are specified in the Wordpress plugin settings.

If those conditions are fulfilled please check the console and send me any errors.

**Comment by blockpac** [comment]
Hi, thanks for your response. These are the errors from my console:

blockstack-common.js:1 Uncaught ReferenceError: require is not defined
    at blockstack-common.js:1
(anonymous) @ blockstack-common.js:1
wp-login.php:80 Uncaught TypeError: Cannot read property 'login' of undefined
    at HTMLInputElement.<anonymous> (wp-login.php:80)
(anonymous) @ wp-login.php:80

**Comment by saul-jb** [comment]
Please use the minified file (blockstack-common.min.js).
The unminified file is for development through node.js and the browser cannot run it (hence the require error).

**Comment by blockpac** [comment]
Thanks, that worked.. as in it redirects me to https://browser.blockstack.org/ even while the local Blockstack app is running on Windows and showing in my system tray? After signing in on https://browser.blockstack.org/ it redirects me to the wp-login.php page of Wordpress and no actual sign in has happened? 

Also can you please explain where exactly to put the header information in the manifest.json file?

_"There must be a manifest page for the blockstack authentication service to access otherwise the service will not work, the manifest must have the server's url and the "Access-Control-Allow-Origin: * " header set"_

I appreciate the time you take to solve this!

**Comment by saul-jb** [comment]
The plugin handles the manifest internally, so you dont need to create or modify this file. Still looking into the sign-in issue.

**Comment by saul-jb** [comment]
Just updated the blockstack-sso lib, pull it and see if it resolves your issue.

**Comment by blockpac** [comment]
It is working now!

Another question: When logging in with Blockstack the user is redirected back to the Admin logon page, not to the main website. Can this redirect destination be set somewhere in the code?

And how can a user see that (s)he is actually logged in on the homepage? The Meta widget doesn't show the user as being logged in. Instead it still shows the 'Log in' link after signing in with Blockstack.

**Comment by saul-jb** [comment]
I am closing _this_ issue as it has been resolved, feel free to open additional issues for other problems.

The redirection can be changed in "pages/auth-page.php", search for "/wp-admin/" (line 124) and change to "/" (home) or "/any-other-page". I may add this as an option in the plugin settings later.

I am unable to replicate your second question, the meta shows the user as being logged in for my tests. Please check that it has actually logged the user in and open another issue with more information on how to replicate it and what settings you have used if it is still an issue.
